# Generated by Django 3.0.2 on 2020-01-11 20:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('started', models.DateTimeField(null=True)),
                ('is_owner_black', models.BooleanField(default=True)),
                ('is_owner_home_right', models.BooleanField(default=True)),
                ('opponent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attended_games', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_games', to=settings.AUTH_USER_MODEL)),
                ('winner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_games', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Board',
            fields=[
                ('game', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='board', serialize=False, to='game.Game')),
                ('black_bead_01_position', models.IntegerField(default=6)),
                ('black_bead_02_position', models.IntegerField(default=6)),
                ('black_bead_03_position', models.IntegerField(default=6)),
                ('black_bead_04_position', models.IntegerField(default=6)),
                ('black_bead_05_position', models.IntegerField(default=6)),
                ('black_bead_06_position', models.IntegerField(default=8)),
                ('black_bead_07_position', models.IntegerField(default=8)),
                ('black_bead_08_position', models.IntegerField(default=8)),
                ('black_bead_09_position', models.IntegerField(default=13)),
                ('black_bead_10_position', models.IntegerField(default=13)),
                ('black_bead_11_position', models.IntegerField(default=13)),
                ('black_bead_12_position', models.IntegerField(default=13)),
                ('black_bead_13_position', models.IntegerField(default=13)),
                ('black_bead_14_position', models.IntegerField(default=24)),
                ('black_bead_15_position', models.IntegerField(default=24)),
                ('white_bead_01_position', models.IntegerField(default=19)),
                ('white_bead_02_position', models.IntegerField(default=19)),
                ('white_bead_03_position', models.IntegerField(default=19)),
                ('white_bead_04_position', models.IntegerField(default=19)),
                ('white_bead_05_position', models.IntegerField(default=19)),
                ('white_bead_06_position', models.IntegerField(default=17)),
                ('white_bead_07_position', models.IntegerField(default=17)),
                ('white_bead_08_position', models.IntegerField(default=17)),
                ('white_bead_09_position', models.IntegerField(default=12)),
                ('white_bead_10_position', models.IntegerField(default=12)),
                ('white_bead_11_position', models.IntegerField(default=12)),
                ('white_bead_12_position', models.IntegerField(default=12)),
                ('white_bead_13_position', models.IntegerField(default=12)),
                ('white_bead_14_position', models.IntegerField(default=1)),
                ('white_bead_15_position', models.IntegerField(default=1)),
            ],
        ),
    ]
