# Generated by Django 3.0.2 on 2020-01-11 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_turn'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['created']},
        ),
        migrations.AlterModelOptions(
            name='turn',
            options={'ordering': ['started']},
        ),
    ]
