# Generated by Django 3.0.2 on 2020-01-11 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20200111_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='turn',
            name='next_turn',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.Turn'),
        ),
    ]
