# Generated by Django 3.0.2 on 2020-01-12 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_game_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='ended',
            field=models.DateTimeField(null=True),
        ),
    ]
