# Generated by Django 3.0.2 on 2020-01-12 02:29

from django.db import migrations
import game.fields


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_game_ended'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='invite_token',
            field=game.fields.RandomStrField(default='dRjav6XEsNkpvz4eNf7JT5Fv', max_length=24),
        ),
    ]
