# Generated by Django 3.0.2 on 2020-01-16 19:46

from django.db import migrations
import game.fields


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_auto_20200116_1942'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='is_owner_home_right',
            new_name='is_owner_home_start',
        ),
        migrations.AlterField(
            model_name='game',
            name='invite_token',
            field=game.fields.RandomStrField(default='vQoTgPmV9u3ZhddkBttSAxqw', max_length=24),
        ),
    ]
