# Generated by Django 3.0.2 on 2020-01-17 00:17

from django.db import migrations
import game.fields
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_auto_20200116_1946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='black_bead_01_position',
        ),
        migrations.RemoveField(
            model_name='board',
            name='black_bead_02_position',
        ),
        migrations.RemoveField(
            model_name='board',
            name='black_bead_03_position',
        ),
        migrations.RemoveField(
            model_name='board',
            name='black_bead_04_position',
        ),
        migrations.RemoveField(
            model_name='board',
            name='black_bead_05_position',
        ),
        migrations.RemoveField(
            model_name='board',
            name='black_bead_06_position',
        ),
        migrations.RemoveField(
            model_name='board',
            name='black_bead_07_position',
        ),
        migrations.RemoveField(
            model_name='board',
            name='black_bead_08_position',
        ),
        migrations.RemoveField(
            model_name='board',
            name='black_bead_09_position',
        ),
        migrations.RemoveField(
            model_name='board',
            name='black_bead_10_position',
        ),
        migrations.RemoveField(
            model_name='board',
            name='black_bead_11_position',
        ),
        migrations.RemoveField(
            model_name='board',
            name='black_bead_12_position',
        ),
        migrations.RemoveField(
            model_name='board',
            name='black_bead_13_position',
        ),
        migrations.RemoveField(
            model_name='board',
            name='black_bead_14_position',
        ),
        migrations.RemoveField(
            model_name='board',
            name='black_bead_15_position',
        ),
        migrations.RemoveField(
            model_name='board',
            name='white_bead_01_position',
        ),
        migrations.RemoveField(
            model_name='board',
            name='white_bead_02_position',
        ),
        migrations.RemoveField(
            model_name='board',
            name='white_bead_03_position',
        ),
        migrations.RemoveField(
            model_name='board',
            name='white_bead_04_position',
        ),
        migrations.RemoveField(
            model_name='board',
            name='white_bead_05_position',
        ),
        migrations.RemoveField(
            model_name='board',
            name='white_bead_06_position',
        ),
        migrations.RemoveField(
            model_name='board',
            name='white_bead_07_position',
        ),
        migrations.RemoveField(
            model_name='board',
            name='white_bead_08_position',
        ),
        migrations.RemoveField(
            model_name='board',
            name='white_bead_09_position',
        ),
        migrations.RemoveField(
            model_name='board',
            name='white_bead_10_position',
        ),
        migrations.RemoveField(
            model_name='board',
            name='white_bead_11_position',
        ),
        migrations.RemoveField(
            model_name='board',
            name='white_bead_12_position',
        ),
        migrations.RemoveField(
            model_name='board',
            name='white_bead_13_position',
        ),
        migrations.RemoveField(
            model_name='board',
            name='white_bead_14_position',
        ),
        migrations.RemoveField(
            model_name='board',
            name='white_bead_15_position',
        ),
        migrations.AddField(
            model_name='board',
            name='beads',
            field=jsonfield.fields.JSONField(default={'black': [6, 6, 6, 6, 6, 8, 8, 8, 13, 13, 13, 13, 13, 24, 24], 'white': [19, 19, 19, 19, 19, 17, 17, 17, 12, 12, 12, 12, 12, 1, 1]}),
        ),
        migrations.AlterField(
            model_name='game',
            name='invite_token',
            field=game.fields.RandomStrField(default='i913ZesCfMcvzR289BTJSxj3', max_length=24),
        ),
    ]
