# Generated by Django 3.0.2 on 2020-01-19 23:36

from django.db import migrations
import game.fields


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_auto_20200117_0017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='is_owner_home_start',
            new_name='is_owner_home_left',
        ),
        migrations.AlterField(
            model_name='game',
            name='invite_token',
            field=game.fields.RandomStrField(default='nGhW4B0nqSfxmteYIEvDVjyy', max_length=24),
        ),
    ]
